CREATE TABLE IF NOT EXISTS [words] (
[finnish] VARCHAR NULL,
[english] VARCHAR NULL,
[russian] VARCHAR NULL,
[chapter] INT NULL
);

INSERT INTO words VALUES
('Hei!','Hello!','Привет!',1),
('ja','and','и',1),
('Tervetuloa!','Welcome!','Добро пожаловать!',1),
('Moi!','Hi!','Привет!',1),
('Anteeksi!','Excuse me!','Простите!',1),
('onko','is','есть ли',1),
('täällä','here','здесь',1),
('suonien kurssi','course in Finnish','курс финского языка',1),
('joo','yes','Да',1),
('Kuka sinä olet?','Who are you?','Кто ты?',1),
('minä','I','я',1),
('olla','be','быть',1),
('entä','what about','а',1),
('sinä','you','ты',1),
('Hauska tutustua!','Nice to meet you!','Очень приятно познакомиться!',1),
('Kiitos samoin!','Likewise!','Спасибо\, мне тоже!',1),
('Mitä sinulle kuuluu?','How are you?','Как дела?',1),
('Minulle kuuluu hyvää.','I’m fine.','У меня все хорошо.',1),
('Entä sinulle?','And you?','А ты как?',1),
('Ihan hyvää\, kiitos\,','I’m fine\, thank you.','Хорошо\, спасибо\,',1),
('hän','he\,she','он/она',1),
('Kuinka vanha sinä olet?','How old are you?','Сколько тебе лет?',1),
('opettaja','teacher','учитель\,учительница',1),
('tulla','(to) come','прийти\,приехать',1),
('Huomenta!','Good morning!','Доброе утро!',1),
('Mikä sinun nimi on?','What’s your name?','Как тебя зовут?',1),
('Minun nimi on...','My name is...','Меня зовут...',1),
('Miten se kirjoitetaan?','How do you spell it?','Как это пишется?',1),
('etunimi','first name','имя',1),
('sukunimi','last name','фамилия',1),
('Huomenta!','Morning!','Доброе утро!',1),
('Hyvää huomenta!','Good morning!','Доброе утро!',1),
('Päivää!','Afternoon!','Здравствуйте!',1),
('Hyvää päivää!','Good afternoon !','Здравствуйте!',1),
('Iltaa!','Evening!','Добрый вечер!',1),
('Hyvää iltaa!','Good evening!','Добрый вечер!',1),
('Hyvää yötä!','Good night!','Спокойной ночи!',1),
('Nuku hyvin!','Sleep well!','Приятных снов!',1),
('Hei!','Hello!','Привет!',1),
('Moi!','Hi!','Привет!',1),
('Terve!','Hi!','Здорово! Привет!',1),
('Nähdään!','See you!','До встречи!',1),
('Hei hei!','Bye bye!','Пока!',1),
('Nähdään huomenna!','See you tomorrow!','Увидимся завтра!',1),
('Moi moi!','Bye bye!','Пока!',1),
('Moikka!','Bye!','Пока!',1),
('Heippa!','Bye!','Пока!',1),
('Näkemiin!','Goodbye!','Пока!',1),
('Joo.','Yeah.','Да.',1),
('Ei.','No.','Нет.',1),
('Kyllä.','Yes.','Да.',1),
('Ole hyvä!','There you are!','Пожалуйста!',1),
('Kiitos!','Thank you!','Спасибо!',1),
('Ei kestä!','You’re welcome!','Не за что!',1),
('Anteeksi!','Sorry!','Простите!',1),
('Ei se mitään!','It’s all right!','Ничего страшного!',1),
('Tervetuloa!','Welcome!','Добро пожаловать!',1),
('viikonpäivät','days of the week','дни недели',1),
('Mikä päivä tänään on?','What day is it today?','Какой сегодня день?',1),
('milloin','when','когда',1),
('Hauskaa viikonloppua!','Have a nice weekend!','Приятных выходных!',1),
('maanantai','Monday','понедельник',1),
('tiistai','Tuesday','вторник',1),
('keskiviikko','Wednesday','среда',1),
('torstai','Thursday','четверг',1),
('perjantai','Friday','пятница',1),
('lauantai','Saturday','суббота',1),
('sunnuntai','Sunday','воскресенье',1),
('viikonloppu','weekend','конец недели (суббота и воскресенье)',1),
('toissapäivänä','day before yesterday','позавчера',1),
('eilen','yesterday','вчера',1),
('tänään','today','сегодня',1),
('huomenna','tomorrow','завтра',1),
('ylihuomenna','day after tomorrow','послезавтра',1),
('nolla','zero','нуль',1),
('yksi','one','один',1),
('kaksi','two','два',1),
('kolme','three','три',1),
('neljä','four','четыре',1),
('viisi','five','пять',1),
('kuusi','six','шесть',1),
('seitsemän','seven','семь',1),
('kahdeksan','eight','восемь',1),
('yhdeksän','nine','девять',1),
('kymmenen','ten','десять',1),
('yksitoista','eleven','одиннадцать',1),
('kaksitoista','twelve','двенадцать',1),
('kolmetoista','thirteen','тринадцать',1),
('neljätoista','fourteen','четырнадцать',1),
('viisitoista','fifteen','пятнадцать',1),
('kuusitoista','sixteen','шестнадцать',1),
('seitsemäntoista','seventeen','семнадцать',1),
('kahdeksantoista','eighteen','восемнадцать',1),
('yhdeksäntoista','nineteen','девятнадцать',1),
('kaksikymmentä','twenty','двадцать',1),
('kaksikymmentäyksi','twenty-one','двадцать один',1),
('kaksikymmentäkaksi','twenty-two','двадцать два',1),
('kolmekymmentä','thirty','тридцать',1),
('neljäkymmentä','forty','сорок',1),
('viisikymmentä','fifty','пятьдесят',1),
('kuusikymmentä','sixty','шестьдесят',1),
('seitsemänkymmentä','seventy','семьдесят',1),
('kahdeksankymmentä','eighty','восемьдесят',1),
('yhdeksänkymmentä','ninety','девяносто',1),
('sata','hundred','сто',1),
('satayksi','one hundred and one','сто один',1),
('kaksisataa','two hundred','двести',1),
('kolmesataa','three hundred','триста',1),
('tuhat','thousand','тысяча',1),
('kaksituhatta','two thousand','две тысячи',1),
('viisisataatuhatta','five hundred thousand','пятьсот тысяч',1),
('miljoona','million','миллион',1),
('kaksi miljoonaa','two million','два миллиона',1),
('puisto','park','парк',2),
('loppua','(to) end','кончиться',2),
('kello','o’clock; clock','1. часы 2. в (сколько) часов 3. колокол',2),
('muu','other','другой',2),
('opiskelija','student','студент',2),
('mennä','(to) go','идти\,ехать',2),
('koti','home','дом',2),
('mutta','but','но',2),
('kioski','kiosk','киоск',2),
('ostaa','(to) buy','купить',2),
('jäätelö','ice cream','мороженое',2),
('maksaa','(to) cost; (to) pay','1. стоить 2. платить',2),
('euro','euro','евро',2),
('säästää','(to) save','1. экономить 2. копить',2),
('raha','money','деньги',2),
('sitten','then','потом',2),
('istua','(to) sit','сидеть',2),
('puhua','(to) speak','говорить',2),
('nauraa','(to) laugh','смеяться',2),
('minkämaalainen','Where are you from?','из какой страны',2),
('brasilialainen','Brazilian','1. бразилец\, бразильянка 2. бразильский',2),
('venäläinen','russian','русский',2),
('entä','what about','а',2),
('mistä','where','откуда',2),
('kotoisin','from','родом',2),
('Etelä-Afrikka','South Africa','Южная Африка',2),
('ai jaa','okay','ах вот как',2),
('kieli','language; tongue','язык',2),
('minun','my','мой',2),
('äidinkieli','mother tongue','родной язык',2),
('englanti','english','английский язык',2),
('myös','also','тоже',2),
('vähän','a little','немного',2),
('espanja','Spanish','испанский язык',2),
('-ko/kö','(expresses a question)','ли (в вопросе)',2),
('sinun','your','твой',2),
('portugali','Portuguese','португальский язык',2),
('ai niin','right','ах да',2),
('tietysti','of course','конечно',2),
('ajaa','(to) drive','ехать\,водить',2),
('auto','car','автомобиль',2),
('bussipysäkki','bus stop','автобусная остановка',2),
('missä','where','где',2),
('asua','(to) live','жить (где)',2),
('numero','number','номер',2),
('vaan','but','а',2),
('nyt','now','сейчас\,теперь',2),
('maksaa','(to) cost; (to) pay','1. стоить 2. платить',2),
('pallo','ball','шар\, мяч',2),
('ahaa','oh\,I see','ясно\, понятно',2),
('haluaisin','1 would like','я хотел бы',2),
('suklaa','chocolate','шоколад',2),
('okei','okay','окей',2),
('sinulle','for you','тебе',2),
('-kin','also','тоже',2),
('vanilja','vanilla','ваниль',2),
('mansikka','strawberry','клубника\, земляника',2),
('selvä','right','ясный\, ясно',2),
('tuleeko muuta','anything else','хотите еще что-нибудь?',2),
('tässä','here','вот\, здесь',2),
('euro','euro','евро',2),
('maa','country; land','1. страна 2. земля',2),
('kansalaisuus','nationality','гражданство',2),
('kieli','language; tongue','язык',2),
('Suomi','Finland','Финляндия',2),
('Ranska','France','Франция',2),
('Kreikka','Greece','Греция',2),
('Islanti','Iceland','Исландия',2),
('Egypti','Egypt','Египет',2),
('Venäjä','Russia','Россия',2),
('Pakistan','Pakistan','Пакистан',2),
('suomalainen','Finnish','1. финн\, финка 2. финский',2),
('ranskalainen','French','1. француз\, француженка 2. французский',2),
('kreikkalainen','Greek','1.грек\,гречанка 2.греческий',2),
('islantilainen','Icelandic','1. исландец\,исландка 2. исландский',2),
('egyptiläinen','Egyptian','1.египтянин\,египтянка 2.египетский',2),
('venäläinen','russian','русский',2),
('pakistanilainen','Pakistani','1. пакистанец\,пакистанка 2.пакистанский',2),
('suomi','Finnish','финский язык',2),
('ranska','French','французский язык',2),
('kreikka','Greek','греческий язык',2),
('islanti','Icelandic','исландский язык',2),
('arabia','Arabic','арабский язык',2),
('venäjä','russian','русский язык',2),
('urdu','Urdu','УРДУ',2),
('Mistä sinä olet kotoisin?','Where are you from?','Откуда ты родом?',2),
('Minkämaalainen sinä olet?','Which country are you from?','Ты из какой страны?',2),
('Mitä kieltä sinä puhut?','What language do you speak?','На каком языке ты говоришь?',2),
('olla kotoisin','come from','быть родом (откуда)',2),
('puhua','(to) speak','говорить',2),
('maailma','world','мир',2),
('pohjoisnapa','North Pole','Северный полюс',2),
('Pohjois-Amerikka','North America','Северная Америка',2),
('Etelä-Amerikka','South America','Южная Америка',2),
('Eurooppa','Europe','Европа',2),
('Afrikka','Africa','Африка',2),
('Aasia','Asia','Азия',2),
('Australia','Australia','Австралия',2),
('Etelämanner','Antarctica','Антарктида',2),
('ilmansuunnat','points of the compass','страны света\, стороны горизонта',2),
('pohjoinen','north','север',2),
('etelä','south','юг',2),
('itä','east','восток',2),
('länsi','west','запад',2),
('hinta','price','цена',2),
('raha','money','деньги',2),
('Mitä tämä maksaa?','How much does this cost?','Сколько это стоит?',2),
('euro','euro','евро',2),
('sentti','cent','цент',2),
('seteli','note\, bill','денежный знак\, купюра',2),
('kolikko','coin','монета',2),
('halpa','cheap','дешевый',2),
('kallis','expensive','дорогой',2);